'use client';

import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from 'react';
import styles from './AdminWriter.module.css';

type Photo = { file: File; preview: string; safeName: string };
type PostSummary = { slug:string; title:string; date:string; category:string; excerpt:string; image:string|null; readingTime:string };
type LoadedPost = PostSummary & { body:string; images:string[] };
const categories = ['Journal','Projects','Photography','Places','Learning','Work'];

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function safeFileName(name:string,index:number){const ext=name.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const base=name.replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`photo-${index+1}`;return `${base}.${ext}`}
function MarkdownPreview({body}:{body:string}){return <div className={styles.previewBody}>{body.split(/\n\n+/).filter(Boolean).map((block,i)=>{if(block.startsWith('### '))return <h3 key={i}>{block.slice(4)}</h3>;if(block.startsWith('## '))return <h2 key={i}>{block.slice(3)}</h2>;if(block.startsWith('> '))return <blockquote key={i}>{block.slice(2)}</blockquote>;if(block.startsWith('- '))return <ul key={i}>{block.split('\n').map((x,j)=><li key={j}>{x.replace(/^- /,'')}</li>)}</ul>;if(block.startsWith('!['))return <p className={styles.imageNote} key={i}>Photo appears here when published.</p>;return <p key={i}>{block}</p>})}</div>}

export default function AdminWriter(){
  const [screen,setScreen]=useState<'posts'|'write'|'preview'>('posts');const [posts,setPosts]=useState<PostSummary[]>([]);const [loadingPosts,setLoadingPosts]=useState(true);const [editingSlug,setEditingSlug]=useState<string|null>(null);
  const [title,setTitle]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [category,setCategory]=useState('Journal');const [excerpt,setExcerpt]=useState('');const [body,setBody]=useState('');
  const [photos,setPhotos]=useState<Photo[]>([]);const [existingImages,setExistingImages]=useState<string[]>([]);const [coverChoice,setCoverChoice]=useState<string|null>(null);const [status,setStatus]=useState('');const [publishing,setPublishing]=useState(false);const textarea=useRef<HTMLTextAreaElement>(null);
  const generatedSlug=useMemo(()=>slugify(title),[title]);const activeSlug=editingSlug??generatedSlug;
  useEffect(()=>{void loadPosts()},[]);
  async function loadPosts(){setLoadingPosts(true);try{const res=await fetch('/api/admin/posts',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load posts');setPosts(data.posts)}catch(e){setStatus(e instanceof Error?e.message:'Could not load posts')}finally{setLoadingPosts(false)}}
  function resetWriter(){photos.forEach(p=>URL.revokeObjectURL(p.preview));setEditingSlug(null);setTitle('');setDate(new Date().toISOString().slice(0,10));setCategory('Journal');setExcerpt('');setBody('');setPhotos([]);setExistingImages([]);setCoverChoice(null);setStatus('');setScreen('write')}
  async function editPost(slug:string){setStatus('Loading post…');try{const res=await fetch(`/api/admin/posts?slug=${encodeURIComponent(slug)}`,{cache:'no-store'});const data=await res.json() as LoadedPost & {error?:string};if(!res.ok)throw new Error(data.error||'Could not load post');setEditingSlug(data.slug);setTitle(data.title);setDate(data.date);setCategory(data.category);setExcerpt(data.excerpt);setBody(data.body);setExistingImages(data.images);setPhotos([]);setCoverChoice(data.image);setStatus('');setScreen('write')}catch(e){setStatus(e instanceof Error?e.message:'Could not load post')}}
  async function deletePost(post:PostSummary){if(!window.confirm(`Delete “${post.title}”?\n\nThis removes the post and its uploaded images from the blog repository.`))return;setStatus(`Deleting ${post.title}…`);try{const res=await fetch('/api/admin/posts',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({slug:post.slug})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Delete failed');setPosts(p=>p.filter(x=>x.slug!==post.slug));setStatus('Deleted. Vercel is deploying the change.')}catch(e){setStatus(e instanceof Error?e.message:'Delete failed')}}
  function addFiles(files:File[]){const images=files.filter(f=>f.type.startsWith('image/'));if(photos.length+images.length>4)return setStatus('Use at most 4 new photos per save.');if(images.some(f=>f.size>1_500_000))return setStatus('Each photo must be 1.5 MB or smaller.');if([...photos.map(p=>p.file),...images].reduce((n,f)=>n+f.size,0)>4_000_000)return setStatus('Keep new photo uploads under 4 MB total.');const next=images.map((file,i)=>({file,preview:URL.createObjectURL(file),safeName:safeFileName(file.name,photos.length+i)}));setPhotos(p=>[...p,...next]);setStatus('')}
  function fileInput(e:ChangeEvent<HTMLInputElement>){addFiles(Array.from(e.target.files??[]))}function drop(e:DragEvent<HTMLDivElement>){e.preventDefault();addFiles(Array.from(e.dataTransfer.files))}
  function insertPhotoPath(path:string){if(!activeSlug)return setStatus('Add a title first so the photo path has a slug.');const markdown=`\n\n![Describe this photo](${path})\n\n`;const el=textarea.current;const start=el?.selectionStart??body.length;setBody(body.slice(0,start)+markdown+body.slice(start))}
  async function save(){if(!title.trim()||!excerpt.trim()||!body.trim())return setStatus('Title, excerpt and article are required.');setPublishing(true);setStatus(editingSlug?'Saving changes…':'Preparing post…');try{const images=await Promise.all(photos.map(async p=>({name:p.safeName,type:p.file.type,data:await fileToBase64(p.file)})));const isEdit=Boolean(editingSlug);const endpoint=isEdit?'/api/admin/posts':'/api/admin/publish';const cover=coverChoice?.startsWith('new:')?coverChoice.slice(4):coverChoice;const payload=isEdit?{originalSlug:editingSlug,title,date,category,excerpt,body,cover,images}:{title,date,category,excerpt,body,cover,images};const res=await fetch(endpoint,{method:isEdit?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||(isEdit?'Save failed':'Publish failed'));setStatus(isEdit?'Saved. Vercel is deploying the update.':`Published. ${data.url}`);if(isEdit)await loadPosts()}catch(e){setStatus(e instanceof Error?e.message:'Save failed')}finally{setPublishing(false)}}
  const previewCover=coverChoice?.startsWith('new:')?photos.find(p=>p.safeName===coverChoice.slice(4))?.preview:coverChoice;

  if(screen==='posts')return <section className={styles.shell}><header className={styles.top}><div><div className="kicker">Private writer</div><h1>Posts</h1></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={resetWriter}>New post</button><form action="/api/admin/logout" method="post"><button className={styles.ghost}>Sign out</button></form></div></header><div style={{marginTop:28,borderTop:'1px solid var(--line)'}}>{loadingPosts?<p className="page-intro">Loading posts…</p>:posts.map(post=><article key={post.slug} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:18,padding:'22px 0',borderBottom:'1px solid var(--line)',alignItems:'center'}}><div><div className="meta">{post.category} · {post.date} · {post.readingTime}</div><h2 style={{fontFamily:'var(--serif)',fontSize:28,fontWeight:500,margin:'7px 0 5px'}}>{post.title}</h2><p style={{color:'var(--muted)',margin:0,lineHeight:1.5}}>{post.excerpt}</p></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={()=>void editPost(post.slug)}>Edit</button><button className={styles.ghost} style={{color:'#a0443e'}} onClick={()=>void deletePost(post)}>Delete</button></div></article>)}</div>{status&&<p style={{marginTop:18}} className={styles.status}>{status}</p>}</section>;

  return <section className={styles.shell}><header className={styles.top}><div><div className="kicker">Private writer</div><h1>{editingSlug?'Edit entry':'New entry'}</h1></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={()=>setScreen('posts')}>All posts</button><form action="/api/admin/logout" method="post"><button className={styles.ghost}>Sign out</button></form></div></header><div className={styles.tabs}><button className={screen==='write'?styles.active:''} onClick={()=>setScreen('write')}>Write</button><button className={screen==='preview'?styles.active:''} onClick={()=>setScreen('preview')}>Preview</button></div>
  {screen==='write'?<div className={styles.editor}><div className={styles.fields}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Something worth remembering" /></label>{editingSlug&&<div className="meta">URL stays /posts/{editingSlug} even if the title changes.</div>}<div className={styles.row}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Excerpt<textarea className={styles.excerpt} value={excerpt} onChange={e=>setExcerpt(e.target.value)} placeholder="One short sentence for the homepage." /></label><label>Article<textarea ref={textarea} className={styles.article} value={body} onChange={e=>setBody(e.target.value)} placeholder={'Write in Markdown…\n\n## A section\n\nYour words here.'} /></label></div><aside><div className={styles.drop} onDragOver={e=>e.preventDefault()} onDrop={drop}><strong>Drop photos here</strong><span>or choose up to 4 new images</span><label className={styles.choose}>Choose photos<input hidden type="file" accept="image/*" multiple onChange={fileInput}/></label><small>1.5 MB each · 4 MB total</small></div>{existingImages.length>0&&<div className={styles.photos}><div className="meta" style={{marginTop:14}}>Existing photos</div>{existingImages.map(path=><div className={styles.photo} key={path}><img src={path} alt=""/><div><button onClick={()=>setCoverChoice(path)}>{coverChoice===path?'Cover ✓':'Make cover'}</button><button onClick={()=>insertPhotoPath(path)}>Insert</button></div></div>)}</div>}<div className={styles.photos}>{photos.map(p=><div className={styles.photo} key={p.preview}><img src={p.preview} alt=""/><div><button onClick={()=>setCoverChoice(`new:${p.safeName}`)}>{coverChoice===`new:${p.safeName}`?'Cover ✓':'Make cover'}</button><button onClick={()=>insertPhotoPath(`/images/posts/${activeSlug}/${p.safeName}`)}>Insert</button><button onClick={()=>setPhotos(x=>x.filter(photo=>photo!==p))}>Remove</button></div></div>)}</div></aside></div>:<article className={styles.preview}><div className="kicker">{category} · {date}</div><h1>{title||'Untitled entry'}</h1><p className={styles.deck}>{excerpt||'Your excerpt will appear here.'}</p>{previewCover&&<img className={styles.cover} src={previewCover} alt=""/>}<MarkdownPreview body={body||'Start writing to see the article preview.'}/></article>}
  <footer className={styles.actions}><span>{editingSlug?`/posts/${editingSlug}`:generatedSlug?`/posts/${generatedSlug}`:'Add a title to create the URL'}</span><span className={styles.status}>{status}</span><button disabled={publishing} onClick={()=>void save()}>{publishing?'Saving…':editingSlug?'Save changes':'Publish'}</button></footer></section>}
function fileToBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
