'use client';

import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import styles from './AdminWriter.module.css';

type Photo = { file: File; preview: string; safeName: string; afterParagraph: number };
type PostSummary = { slug:string; title:string; date:string; category:string; excerpt:string; image:string|null; readingTime:string };
type LoadedPost = PostSummary & { body:string; images:string[] };
const categories = ['Journal','Projects','Photography','Places','Learning','Work'];

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function safeFileName(name:string,index:number,prefix='media'){const ext=name.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const base=name.replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`${prefix}-${index+1}`;return `${prefix}-${base}.${ext}`}
function escapeRegExp(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function paragraphCount(value:string){return value.split(/\n\s*\n/).map(x=>x.trim()).filter(x=>x&&!/^!\[[^\]]*\]\([^)]*\)$/.test(x)&&!/^#{1,6}\s/.test(x)).length}
function placeImage(body:string,path:string,afterParagraph:number){
  const escaped=escapeRegExp(path);
  const without=body.replace(new RegExp(`\\n*!\\[[^\\]]*\\]\\(${escaped}\\)\\n*`,'g'),'\n\n').trim();
  const blocks=without.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);
  const paragraphs=blocks.map((block,index)=>({block,index})).filter(x=>!/^!\[[^\]]*\]\([^)]*\)$/.test(x.block)&&!/^#{1,6}\s/.test(x.block));
  if(paragraphs.length===0)return `${without}${without?'\n\n':''}![Article image](${path})`;
  const target=Math.max(1,Math.min(afterParagraph,paragraphs.length));
  const insertAt=paragraphs[target-1].index+1;
  blocks.splice(insertAt,0,`![Article image](${path})`);
  return blocks.join('\n\n');
}
function MarkdownPreview({body}:{body:string}){return <div className={styles.previewBody}>{body.split(/\n\n+/).filter(Boolean).map((block,i)=>{if(block.startsWith('### '))return <h3 key={i}>{block.slice(4)}</h3>;if(block.startsWith('## '))return <h2 key={i}>{block.slice(3)}</h2>;if(block.startsWith('> '))return <blockquote key={i}>{block.slice(2)}</blockquote>;if(block.startsWith('- '))return <ul key={i}>{block.split('\n').map((x,j)=><li key={j}>{x.replace(/^- /,'')}</li>)}</ul>;if(block.startsWith('!['))return <p className={styles.imageNote} key={i}>Article image</p>;return <p key={i}>{block}</p>})}</div>}

export default function AdminWriter(){
  const [screen,setScreen]=useState<'posts'|'write'|'preview'>('posts');const [posts,setPosts]=useState<PostSummary[]>([]);const [loadingPosts,setLoadingPosts]=useState(true);const [editingSlug,setEditingSlug]=useState<string|null>(null);
  const [title,setTitle]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [category,setCategory]=useState('Journal');const [excerpt,setExcerpt]=useState('');const [body,setBody]=useState('');
  const [thumbnail,setThumbnail]=useState<Photo|null>(null);const [media,setMedia]=useState<Photo[]>([]);const [existingImages,setExistingImages]=useState<string[]>([]);const [existingCover,setExistingCover]=useState<string|null>(null);const [existingPlacement,setExistingPlacement]=useState<Record<string,number>>({});
  const [status,setStatus]=useState('');const [publishing,setPublishing]=useState(false);
  const generatedSlug=useMemo(()=>slugify(title),[title]);const activeSlug=editingSlug??generatedSlug;const paragraphs=useMemo(()=>paragraphCount(body),[body]);
  useEffect(()=>{void loadPosts()},[]);
  async function loadPosts(){setLoadingPosts(true);try{const res=await fetch('/api/admin/posts',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load posts');setPosts(data.posts)}catch(e){setStatus(e instanceof Error?e.message:'Could not load posts')}finally{setLoadingPosts(false)}}
  function revoke(photo:Photo|null){if(photo)URL.revokeObjectURL(photo.preview)}
  function resetWriter(){revoke(thumbnail);media.forEach(revoke);setEditingSlug(null);setTitle('');setDate(new Date().toISOString().slice(0,10));setCategory('Journal');setExcerpt('');setBody('');setThumbnail(null);setMedia([]);setExistingImages([]);setExistingCover(null);setExistingPlacement({});setStatus('');setScreen('write')}
  async function editPost(slug:string){setStatus('Loading post…');try{const res=await fetch(`/api/admin/posts?slug=${encodeURIComponent(slug)}`,{cache:'no-store'});const data=await res.json() as LoadedPost & {error?:string};if(!res.ok)throw new Error(data.error||'Could not load post');setEditingSlug(data.slug);setTitle(data.title);setDate(data.date);setCategory(data.category);setExcerpt(data.excerpt);setBody(data.body);setExistingImages(data.images);setExistingCover(data.image);setThumbnail(null);setMedia([]);setExistingPlacement({});setStatus('');setScreen('write')}catch(e){setStatus(e instanceof Error?e.message:'Could not load post')}}
  async function deletePost(post:PostSummary){if(!window.confirm(`Delete “${post.title}”?\n\nThis removes the post and its uploaded images from the blog repository.`))return;setStatus(`Deleting ${post.title}…`);try{const res=await fetch('/api/admin/posts',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({slug:post.slug})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Delete failed');setPosts(p=>p.filter(x=>x.slug!==post.slug));setStatus('Deleted. Vercel is deploying the change.')}catch(e){setStatus(e instanceof Error?e.message:'Delete failed')}}
  function validateFile(file:File){if(!file.type.startsWith('image/'))return 'Choose an image file.';if(file.size>1_500_000)return 'Each image must be 1.5 MB or smaller.';return ''}
  function thumbnailInput(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const error=validateFile(file);if(error)return setStatus(error);revoke(thumbnail);setThumbnail({file,preview:URL.createObjectURL(file),safeName:safeFileName(file.name,0,'thumbnail'),afterParagraph:1});setStatus('')}
  function mediaInput(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]).filter(f=>f.type.startsWith('image/'));if(media.length+files.length>6)return setStatus('Use at most 6 article images per save.');if(files.some(f=>f.size>1_500_000))return setStatus('Each image must be 1.5 MB or smaller.');if([...media.map(p=>p.file),...files].reduce((n,f)=>n+f.size,0)+(thumbnail?.file.size??0)>6_000_000)return setStatus('Keep new image uploads under 6 MB total.');const fallback=Math.max(1,paragraphs);const next=files.map((file,i)=>({file,preview:URL.createObjectURL(file),safeName:safeFileName(file.name,media.length+i,'media'),afterParagraph:fallback}));setMedia(p=>[...p,...next]);setStatus('')}
  function applyMediaPlacement(photo:Photo){if(!activeSlug)return setStatus('Add a title first so image paths can be created.');if(paragraphs===0)return setStatus('Write at least one paragraph before placing article images.');const path=`/images/posts/${activeSlug}/${photo.safeName}`;setBody(current=>placeImage(current,path,photo.afterParagraph));setStatus(`Placed ${photo.safeName} after paragraph ${photo.afterParagraph}.`)}
  function applyExistingPlacement(path:string){if(paragraphs===0)return setStatus('Write at least one paragraph before placing article images.');const after=existingPlacement[path]??Math.max(1,paragraphs);setBody(current=>placeImage(current,path,after));setStatus(`Moved image after paragraph ${after}.`)}
  async function save(){if(!title.trim()||!excerpt.trim()||!body.trim())return setStatus('Title, excerpt and article are required.');if(!editingSlug&&!thumbnail)return setStatus('A thumbnail image is required before publishing.');if(editingSlug&&!thumbnail&&!existingCover)return setStatus('This post needs a thumbnail image before it can be saved.');setPublishing(true);setStatus(editingSlug?'Saving changes…':'Preparing post…');try{
    const uploads:Photo[]=[...(thumbnail?[thumbnail]:[]),...media];const images=await Promise.all(uploads.map(async p=>({name:p.safeName,type:p.file.type,data:await fileToBase64(p.file)})));const isEdit=Boolean(editingSlug);const endpoint=isEdit?'/api/admin/posts':'/api/admin/publish';const cover=thumbnail?thumbnail.safeName:existingCover;const payload=isEdit?{originalSlug:editingSlug,title,date,category,excerpt,body,cover,images}:{title,date,category,excerpt,body,cover,images};const res=await fetch(endpoint,{method:isEdit?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||(isEdit?'Save failed':'Publish failed'));setStatus(isEdit?'Saved. Vercel is deploying the update.':`Published. ${data.url}`);if(isEdit)await loadPosts()}catch(e){setStatus(e instanceof Error?e.message:'Save failed')}finally{setPublishing(false)}}
  const previewCover=thumbnail?.preview??existingCover;

  if(screen==='posts')return <section className={styles.shell}><header className={styles.top}><div><div className="kicker">Private writer</div><h1>Posts</h1></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={resetWriter}>New post</button><form action="/api/admin/logout" method="post"><button className={styles.ghost}>Sign out</button></form></div></header><div style={{marginTop:28,borderTop:'1px solid var(--line)'}}>{loadingPosts?<p className="page-intro">Loading posts…</p>:posts.map(post=><article key={post.slug} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:18,padding:'22px 0',borderBottom:'1px solid var(--line)',alignItems:'center'}}><div><div className="meta">{post.category} · {post.date} · {post.readingTime}</div><h2 style={{fontFamily:'var(--serif)',fontSize:28,fontWeight:500,margin:'7px 0 5px'}}>{post.title}</h2><p style={{color:'var(--muted)',margin:0,lineHeight:1.5}}>{post.excerpt}</p></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={()=>void editPost(post.slug)}>Edit</button><button className={styles.ghost} style={{color:'#a0443e'}} onClick={()=>void deletePost(post)}>Delete</button></div></article>)}</div>{status&&<p style={{marginTop:18}} className={styles.status}>{status}</p>}</section>;

  return <section className={styles.shell}><header className={styles.top}><div><div className="kicker">Private writer</div><h1>{editingSlug?'Edit entry':'New entry'}</h1></div><div style={{display:'flex',gap:8}}><button className={styles.ghost} onClick={()=>setScreen('posts')}>All posts</button><form action="/api/admin/logout" method="post"><button className={styles.ghost}>Sign out</button></form></div></header><div className={styles.tabs}><button className={screen==='write'?styles.active:''} onClick={()=>setScreen('write')}>Write</button><button className={screen==='preview'?styles.active:''} onClick={()=>setScreen('preview')}>Preview</button></div>
  {screen==='write'?<div className={styles.editor}><div className={styles.fields}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Something worth remembering" /></label>{editingSlug&&<div className="meta">URL stays /posts/{editingSlug} even if the title changes.</div>}<div className={styles.row}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Excerpt<textarea className={styles.excerpt} value={excerpt} onChange={e=>setExcerpt(e.target.value)} placeholder="One short sentence for the homepage." /></label><label>Article <span className={styles.paragraphHint}>{paragraphs} paragraphs detected</span><textarea className={styles.article} value={body} onChange={e=>setBody(e.target.value)} placeholder={'Write in Markdown…\n\nLeave a blank line between paragraphs.\n\nArticle images can be placed after any paragraph.'} /></label></div><aside className={styles.mediaRail}>
    <section className={styles.mediaSection}><div className={styles.mediaHeading}><strong>Thumbnail</strong><span>Required</span></div><p className={styles.mediaHelp}>Used on the homepage and as the post cover.</p>{previewCover&&<img className={styles.thumbnailPreview} src={previewCover} alt="Current thumbnail"/>}<label className={styles.choose}>{thumbnail?'Replace thumbnail':'Choose thumbnail'}<input hidden type="file" accept="image/*" onChange={thumbnailInput}/></label>{thumbnail&&<button className={styles.removeButton} onClick={()=>{revoke(thumbnail);setThumbnail(null)}}>Remove new thumbnail</button>}</section>
    <section className={styles.mediaSection}><div className={styles.mediaHeading}><strong>Article media</strong><span>Optional</span></div><p className={styles.mediaHelp}>Upload images, then choose the paragraph each one should follow.</p><label className={styles.choose}>Add article images<input hidden type="file" accept="image/*" multiple onChange={mediaInput}/></label>
      {media.map(photo=><div className={styles.placementCard} key={photo.preview}><img src={photo.preview} alt=""/><label>Place after paragraph<input type="number" min={1} max={Math.max(1,paragraphs)} value={photo.afterParagraph} onChange={e=>setMedia(items=>items.map(x=>x===photo?{...x,afterParagraph:Number(e.target.value)||1}:x))}/></label><div><button onClick={()=>applyMediaPlacement(photo)}>Place / move</button><button onClick={()=>{revoke(photo);setMedia(items=>items.filter(x=>x!==photo))}}>Remove</button></div></div>)}
      {existingImages.filter(path=>path!==existingCover).length>0&&<><div className={styles.subHeading}>Existing article images</div>{existingImages.filter(path=>path!==existingCover).map(path=><div className={styles.placementCard} key={path}><img src={path} alt=""/><label>Place after paragraph<input type="number" min={1} max={Math.max(1,paragraphs)} value={existingPlacement[path]??Math.max(1,paragraphs)} onChange={e=>setExistingPlacement(v=>({...v,[path]:Number(e.target.value)||1}))}/></label><button onClick={()=>applyExistingPlacement(path)}>Place / move</button></div>)}</>}
    </section>
  </aside></div>:<article className={styles.preview}><div className="kicker">{category} · {date}</div><h1>{title||'Untitled entry'}</h1><p className={styles.deck}>{excerpt||'Your excerpt will appear here.'}</p>{previewCover&&<img className={styles.cover} src={previewCover} alt=""/>}<MarkdownPreview body={body||'Start writing to see the article preview.'}/></article>}
  <footer className={styles.actions}><span>{editingSlug?`/posts/${editingSlug}`:generatedSlug?`/posts/${generatedSlug}`:'Add a title to create the URL'}</span><span className={styles.status}>{status}</span><button disabled={publishing} onClick={()=>void save()}>{publishing?'Saving…':editingSlug?'Save changes':'Publish'}</button></footer></section>}
function fileToBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
